name: QA Checks

on:
  pull_request:
    paths: ["blogs/**/*.md"]

jobs:
  prettier:
    name: Format Markdown Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1

      - name: Run Oxfmt
        run: npx oxfmt "./blogs" --check
